ticker: YPF
period: 5y
days_back_target: 1
start_money: 100

param_grid:
    objective: ['binary:logistic']
    max_depth: [2, 5, 10]
    n_estimators: [5, 10, 20, 30, 40, 50, 70, 100]
    learning_rate: [0.05, 0.01, 0.1]

train_window: 30 # tamanio de la ventana
train_period: 1 # frecuencia con la que se entrena

trading_strategy: strategies.machine_learning_strategy

threshold_up: 0.85
threshold_down: 0.15

only_one_tunning: True