
models: ['logistic_regression', 'random_forest', 'gradient_boosting']

param_grid:
    objective: ['binary:logistic']
    max_depth: [2, 5, 10]
    n_estimators: [5, 10, 20, 30, 40, 50, 70, 100]
    learning_rate: [0.05, 0.01, 0.1]

train_window: [30, 60, 90] # tamanio de la ventana
train_period: [1, 7, 14, 30] # frecuencia con la que se entrena

trading_strategy: ['strategies.sma_ml_strategy', 'strategies.bb_ml_strategy', 'strategies.macd_ml_strategy']

threshold_up: 0.85
threshold_down: 0.15

only_one_tunning: True