models: [
  'random_forest', 
  'gradient_boosting'
]

train_window: [
  24, # Una semana 
  48,
  72 
] # tamanio de la ventana de entrenamiento

train_period: [
  1, 
] # frecuencia con la que se entrena

stop_loss_in_pips: [
  15, 
]

take_profits_in_pips: [
  30, 
  45, 
]

periods_forward_target: [
  1,
  2,
  4,
  8,
]

use_days_in_position: [
  # True,
  False
]

trading_strategy: [
  'backbone.strategies.macd_strategy',
  'backbone.strategies.bband_strategy', 
]