models: [
  'random_forest', 
  'gradient_boosting'
  ]

train_window: [
    38, # un mes
    76, # dos meses
  ] # tamanio de la ventana de entrenamiento

train_period: [
  1, 
  7, 
  14, 
  ] # frecuencia con la que se entrena

stop_loss_in_pips: [
  15, 
  ]

take_profits_in_pips: [
  30, 
  ]
periods_forward_target: [
  1,
  5,
  10,
]

use_days_in_position: [
  # True,
  False
]

trading_strategy: [
    'strategies.macd_strategy',
    'strategies.bband_strategy', 
  ]



