mode: train
# date_from: '2013-01-01'
date_from: '2023-01-01'
date_to: '2024-01-01'
limit_date_train: '2023-08-01'
tickers: [YPF, BBAR, BMA, CEPU, EDN, TEO, LOMA]
period: 5y
days_forward_target: 10
start_money: 100
threshold_up: 0.5
threshold_down: 0.5
