mode: train
limit_date_train: '2024-04-30'
tickers: [EURUSD, GBPUSD, USDJPY]
period: 5y
start_money: 100
threshold_up: 0.85
threshold_down: 0.15
risk_percentage: 1

# EUR/USD.
# USD/JPY.
# GBP/USD.
# USD/CAD.
# AUD/USD.
